apiVersion: v1
entries:
  my-app:
  - apiVersion: v1
    appVersion: "1.0"
    name: my-app
    urls:
    - https://github.com/maximkoshel/ArgoCD-Test/blob/main/tgz/airflow-8.7.1.tgz
    version: 0.1.0
