apiVersion: v1
entries:
  airflow:
  - apiVersion: v2
    appVersion: 2.5.3
    created: "2023-06-13T17:17:41.5128385+03:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.helm.sh/stable
      version: 8.6.4
    - condition: redis.enabled
      name: redis
      repository: https://charts.helm.sh/stable
      version: 10.5.7
    description: Airflow Helm Chart (User Community) - the standard way to deploy
      Apache Airflow on Kubernetes with Helm
    digest: 1bc14642e89d4740b83c0c1d1210a298447f2b2603aa7a039a6c019d4ad579f1
    home: https://github.com/airflow-helm/charts/tree/main/charts/airflow
    icon: https://avatars.githubusercontent.com/u/71061241
    keywords:
    - airflow
    - dag
    - workflow
    maintainers:
    - name: thesuperzapper
      url: https://github.com/thesuperzapper
    name: airflow
    sources:
    - https://github.com/airflow-helm/charts/tree/main/charts/airflow
    urls:
    - https://github.com/maximkoshel/ArgoCD-Test/tree/main/tgz/airflow-8.7.1.tgz
    version: 8.7.1
generated: "2023-06-13T17:17:41.501883+03:00"
